#! /bin/sh

backtitle="An Example for the use of --inputmenu:"



returncode=0
while test $returncode != 1 && test $returncode != 250
do
	exec 3>&1
	value=`$DIALOG --clear --ok-label "Create" \
	--backtitle "$backtitle" "$@" \
	--inputmenu "123" \
	20 50 10 \
	"Dominio:"	"$DOMINIO" \
	"DocumentRoot:"	"$DOCUMENTROOT" \
	"ErrorLog:"	"$ERRORLOG" \
	"AccessLog:"	"$ACCESSLOG" \
	2>&1 1>&3`
	returncode=$?
	exec 3>&-

	case $returncode in
		$DIALOG_CANCEL)
		"$DIALOG" \
		--clear \
		--backtitle "$backtitle" \
		--yesno "Really quit?" 10 30
		case $? in
			$DIALOG_OK)
			break
			;;
			$DIALOG_CANCEL)
			returncode=99
			;;
		esac
		;;
		$DIALOG_OK)
		"$DIALOG" \
		--clear \
		--backtitle "$backtitle" \
		--msgbox "$DOMINIO \n\
		$DOCUMENTROOT \n\
		$ACCESSLOG \n\
		$ERRORLOG \n\
		" 10 40
		;;
		$DIALOG_EXTRA)
		tag=`echo "$value" |sed -e 's/^RENAMED //' -e 's/:.*//'`
		item=`echo "$value" |sed -e 's/^[^:]*:[ ]*//' -e 's/[ ]*$//'`

		case "$tag" in
			Dominio)
			DOMINIO="$item"
			DOCUMENTROOT="/var/www/$item"
			;;
			DocumentRoot)
			DOCUMENTROOT="$item"
			;;
			ErrorLog)
			ERRORLOG="$item"
			;;
			AccessLog)
			ACCESSLOG="$item"
			;;
		esac
		;;

		$DIALOG_ESC)
		echo "ESC pressed."
		break
		;;

	esac
done
